// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
    "/liquidity/add/[[...poolId]]": InferRoute<import("./src/pages/liquidity/add/[[...poolId]]").RouteType>;
    "/liquidity/create/[...selectId]": InferRoute<import("./src/pages/liquidity/create/[...selectId]").RouteType>;
    "/liquidity/position/[[...positionId]]": InferRoute<import("./src/pages/liquidity/position/[[...positionId]]").RouteType>;
    "/liquidity/select/pools/[[...selectId]]": InferRoute<import("./src/pages/liquidity/select/pools/[[...selectId]]").RouteType>;
    "/liquidity/select/[[...selectId]]": InferRoute<import("./src/pages/liquidity/select/[[...selectId]]").RouteType>;
  }

  interface StaticRouter {
    "/404": StaticRoute;
    "/451": StaticRoute;
    "/add/[[...currency]]": StaticRoute;
    "/cake-staking/redeem": StaticRoute;
    "/farms/history": StaticRoute;
    "/farms": StaticRoute;
    "/increase/[[...currency]]": StaticRoute;
    "/": StaticRoute;
    "/liquid-staking": StaticRoute;
    "/liquid-staking/request-withdraw/[contract]": StaticRoute;
    "/liquid-staking/[contract]": StaticRoute;
    "/liquidity/create": StaticRoute;
    "/liquidity": StaticRoute;
    "/liquidity/pool/[chainName]/[id]": StaticRoute;
    "/liquidity/pools": StaticRoute;
    "/liquidity/positions": StaticRoute;
    "/liquidity/[tokenId]": StaticRoute;
    "/nbc-staking/history": StaticRoute;
    "/nbc-staking": StaticRoute;
    "/pools/history": StaticRoute;
    "/pools": StaticRoute;
    "/pools/[chainName]/[id]": StaticRoute;
    "/remove/[tokenId]": StaticRoute;
    "/stable/add/[[...currency]]": StaticRoute;
    "/stable/remove/[[...currency]]": StaticRoute;
    "/stable/[address]": StaticRoute;
    "/terms-of-service": StaticRoute;
    "/v2/add/[[...currency]]": StaticRoute;
    "/v2/migrate/[address]": StaticRoute;
    "/v2/pair/[[...currency]]": StaticRoute;
    "/v2/remove/[[...currency]]": StaticRoute;
  }
}
